### ISSUE TITLE
Multi-Select Picklist

### ISSUE THREAD

**Issue by kechetino** [berehovskyi/apex-stream#4]
Is there a method that supports Multi-Select Picklists?

I would like to check for instance if any of the AccountContactRelation.Roles values is contained in a list.

Thanks.

**Comment by berehovskyi** [comment]
Hi @kechetino 

Thank you for raising such a good idea.
I have added `includes` and `excludes` SObjectPredicates to filter multi-select picklists to the latest release.

For instance:
```apex
AccountContactRelation rel1 = new AccountContactRelation(Roles = 'AAA;BBB');
AccountContactRelation rel2 = new AccountContactRelation(Roles = 'CCC');
AccountContactRelation rel3 = new AccountContactRelation(Roles = 'AAA;CCC');
AccountContactRelation rel4 = new AccountContactRelation(Roles = 'AAA');
AccountContactRelation rel5 = new AccountContactRelation(Roles = 'AAA;DDD');
List<AccountContactRelation> relations = new List<AccountContactRelation>{ rel1, rel2, rel3, rel4, rel5 };

List<AccountContactRelation> filteredRelations = Stream.of(relations)
    .filter(SObjectPredicates(AccountContactRelation.Roles, new Set<String>{ 'AAA;BBB', 'CCC' })
    .toList(); // [rel1, rel2, rel3]
```
The idea is the same as described in [Query Multi-Select Picklists](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_querying_multiselect_picklists.htm#topic-title)

I will update the README file with examples later.

Best regards.

**Comment by berehovskyi** [comment]
Hi @kechetino 

Thank you for raising such a good idea.
I have added `includes` and `excludes` SObjectPredicates to filter multi-select picklists to the latest release.

For instance:
```apex
AccountContactRelation rel1 = new AccountContactRelation(Roles = 'AAA;BBB');
AccountContactRelation rel2 = new AccountContactRelation(Roles = 'CCC');
AccountContactRelation rel3 = new AccountContactRelation(Roles = 'AAA;CCC');
AccountContactRelation rel4 = new AccountContactRelation(Roles = 'AAA');
AccountContactRelation rel5 = new AccountContactRelation(Roles = 'AAA;DDD');
List<AccountContactRelation> relations = new List<AccountContactRelation>{ rel1, rel2, rel3, rel4, rel5 };

List<AccountContactRelation> filteredRelations = Stream.of(relations)
    .filter(SObjectPredicates(AccountContactRelation.Roles, new Set<String>{ 'AAA;BBB', 'CCC' })
    .toList(); // [rel1, rel2, rel3]
```
The idea is the same as described in [Query Multi-Select Picklists](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_querying_multiselect_picklists.htm#topic-title)

I will update the README file with examples later.

Best regards.

**Comment by berehovskyi** [comment]
Hi @kechetino 

Thank you for raising such a good idea.
I have added `includes` and `excludes` SObjectPredicates to filter multi-select picklists to the latest release.

For instance:
```apex
AccountContactRelation rel1 = new AccountContactRelation(Roles = 'AAA;BBB');
AccountContactRelation rel2 = new AccountContactRelation(Roles = 'CCC');
AccountContactRelation rel3 = new AccountContactRelation(Roles = 'AAA;CCC');
AccountContactRelation rel4 = new AccountContactRelation(Roles = 'AAA');
AccountContactRelation rel5 = new AccountContactRelation(Roles = 'AAA;DDD');
List<AccountContactRelation> relations = new List<AccountContactRelation>{ rel1, rel2, rel3, rel4, rel5 };

List<AccountContactRelation> filteredRelations = Stream.of(relations)
    .filter(SObjectPredicates(AccountContactRelation.Roles, new Set<String>{ 'AAA;BBB', 'CCC' })
    .toList(); // [rel1, rel2, rel3]
```
The idea is the same as described in [Query Multi-Select Picklists](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_querying_multiselect_picklists.htm#topic-title)

I will update the README file with examples later.

Best regards.

**Comment by kechetino** [comment]
Hi @berehovskyi,

Thank you so much! This will be very helpful to us.
