### ISSUE TITLE
Salesforce doesn't support generic type <T>

### ISSUE THREAD

**Issue by konradbeck-creditech** [berehovskyi/apex-stream#5]
https://github.com/berehovskyi/apex-stream/blob/main/sfdx-source/apex-stream/enumerables/main/classes/core/base/INumberEnumerable.cls

public interface INumberEnumerable<T> extends Iterable<T>

**Comment by berehovskyi** [comment]
Hi konradbeck,

Thank you for opening this issue. Could you please provide more details about the problem you encountered?

**Comment by konradbeck-creditech** [comment]
Hi Oleh,

I'm trying to deploy sfdx-source/apex-stream/enumerables/main/classes/core/base/IEnumerable.cls

And get the following "Compile Error: Type parameters are not supported"

I don't think Salesforce allows Iterable<T> but instead requires Iterable<Object>

**Comment by berehovskyi** [comment]
For your current project, I recommend setting the API version of IEnumerable.cls and INumberEnumerable.cls back to the version defined in the project, as these classes use parameterized interfaces to extend the functionality of the Iterable class through Streams and Sequences.

You can safely update the API versions for all other classes in the project, but please make sure that these two specific interface classes remain at the earlier version to maintain compatibility and functionality.

**Comment by berehovskyi** [comment]
I added ApexDoc notes in internal classes to indicate that they should not be referenced outside the package and that the API version of parameterized interfaces should not be updated. All the changes are included in the latest release.
