### ISSUE TITLE
README

### ISSUE THREAD

**Issue by konradbeck-creditech** [berehovskyi/apex-stream#6]
Hello Oleh,

This isn't an issue, I just don't know where else to ask it.

But what tool do you use to create the README?

**Comment by berehovskyi** [comment]
Hi @konradbeck-creditech,

Thank you for reaching out! I use IntelliJ IDEA for editing `.md` files, which makes it easier to create and manage the README files. If you’re new to Markdown, you might find it helpful to check out the [Markdown Basic Syntax](https://www.markdownguide.org/basic-syntax/) for a quick overview.

Best regards.
